spring:
  servlet:
    multipart:
      enabled: true
      max-request-size: 215MB
      file-size-threshold: 2KB
      max-file-size: 200MB
  profiles:
    group:
      local: h2 # possible values: h2, postgresql, gensql
      prod: prod
springdoc:
  api-docs:
    path: /gs-docs
site:
  urls:
    base-url: "http://localhost:8080"
  paths:
    upload-dir: "./public/uploads"
server:
  port: 8080
