spring:
  servlet:
    multipart:
      enabled: true
      max-request-size: 215MB
      file-size-threshold: 2KB
      max-file-size: 200MB
  datasource:
    url: jdbc:h2:mem:gamestore
    username: sa
    password: abc123
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    active: dev # change to 'prod' to apply the production configuration
site:
  api-url: "http://localhost:8080"
server:
  port: 8080
file:
  upload-dir: "./public/uploads"
