spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
site:
  urls:
    base-url: "https://game-store-springboot.herokuapp.com"