spring:
  flyway:
    enabled: true
    locations: classpath:sql/postgresql-migration
    table: SCHEMA_VERSION
    validate-on-migrate: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pw
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
    defer-datasource-initialization: 'false'
    hibernate:
      ddl-auto: none
